In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4254, 2421, 7973, 8125],
 [4254, 2421, 7973, 5227],
 [4254, 3252, 7973, 5844],
 [6903, 9976, 8217, 2415, 1385],
 [6903, 9976, 8217, 2415, 7211],
 [1028, 4254, 6653, 7973, 997],
 [5807, 7851, 7931, 2415]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4254 2421 7973 8125]
 [   0    0    0    0 4254 2421 7973 5227]
 [   0    0    0    0 4254 3252 7973 5844]
 [   0    0    0 6903 9976 8217 2415 1385]
 [   0    0    0 6903 9976 8217 2415 7211]
 [   0    0    0 1028 4254 6653 7973  997]
 [   0    0    0    0 5807 7851 7931 2415]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\simple_rnn_imdb\venvi\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[-3.28182727e-02, -2.41827965e-03,  1.86328627e-02,
          4.00700420e-03, -8.87694210e-03,  3.79293039e-03,
         -3.02557107e-02,  1.18141398e-02,  4.62348200e-02,
          2.64561176e-03],
        [-3.28182727e-02, -2.41827965e-03,  1.86328627e-02,
          4.00700420e-03, -8.87694210e-03,  3.79293039e-03,
         -3.02557107e-02,  1.18141398e-02,  4.62348200e-02,
          2.64561176e-03],
        [-3.28182727e-02, -2.41827965e-03,  1.86328627e-02,
          4.00700420e-03, -8.87694210e-03,  3.79293039e-03,
         -3.02557107e-02,  1.18141398e-02,  4.62348200e-02,
          2.64561176e-03],
        [-3.28182727e-02, -2.41827965e-03,  1.86328627e-02,
          4.00700420e-03, -8.87694210e-03,  3.79293039e-03,
         -3.02557107e-02,  1.18141398e-02,  4.62348200e-02,
          2.64561176e-03],
        [ 1.43036507e-02,  2.05294825e-02,  1.80491693e-02,
         -4.35207039e-03, -3.49597223e-02, -1.96629763e-02,
          3.27817239e-02,  4.11499180e-02, -3.575193

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4254, 2421, 7973, 8125], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None